[profile.default]
src = "src"
out = "out"
libs = ["lib"]
<<<<<<< HEAD
remappings = ["@openzeppelin=lib/openzeppelin-contracts"]
=======
>>>>>>> fd97e2f (a)

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
